[package]
name = "kite-tools"
version = "1.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
clap = { version = "4.5.30", features = ["derive"] }
crossterm = "0.28.1"
anyhow = "1.0.96"
thiserror = "2.0.11"
textwrap = "0.16.1"
sysinfo = "0.33.1"
lazy_static = "1.5.0"