[package]
name = "kite-tools"
version = "1.1.1"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
clap = { version = "4.5.43", features = ["derive"] }
crossterm = "0.29.0"
anyhow = "1.0.98"
thiserror = "2.0.12"
textwrap = "0.16.2"
sysinfo = "0.36.1"
lazy_static = "1.5.0"